#!/bin/bash
# Velo Development Setup Script - Single Source of Truth
# Run this script once after cloning the repo to set up your development environment.
#
# Usage: ./setup-dev.sh

set -euo pipefail

echo "🚀 Velo Development Setup"
echo "========================="
echo

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Check for required tools
check_tool() {
    if ! command -v "$1" &> /dev/null; then
        echo -e "${RED}❌ $1 is required but not installed.${NC}"
        echo "   Install: $2"
        exit 1
    fi
    echo -e "${GREEN}✅${NC} $1 found"
}

echo "📋 Checking required tools..."
check_tool "cargo" "https://rustup.rs"
check_tool "uv" "curl -LsSf https://astral.sh/uv/install.sh | sh"

# Install Rust toolchain (version locked in rust-toolchain.toml)
echo
echo "🔧 Installing Rust toolchain..."
rustup show active-toolchain || rustup default stable
rustup component add clippy rustfmt llvm-tools-preview 2>/dev/null || true

# Install Linux cross-target for pre-commit checks (catches #[cfg(linux)] bugs on macOS)
echo "🐧 Installing Linux cross-compilation target..."
rustup target add x86_64-unknown-linux-gnu

# Create Python venv and install deps from pyproject.toml (Single Source of Truth)
echo
if [[ -f "pyproject.toml" ]]; then
    echo "🐍 Setting up Python environment from pyproject.toml..."
    uv venv
    uv sync  # Single source: pyproject.toml
    echo -e "${GREEN}✅${NC} Python environment ready"
else
    echo "🐍 No pyproject.toml found, skipping Python setup."
fi

# Configure PYO3_PYTHON for cargo build (RSGI/Granian native worker support)
# This ensures PyO3 links against the SAME Python that uv uses at runtime
echo
if [[ -f "pyproject.toml" ]]; then
    echo "🔗 Configuring PyO3 Python..."
    # Use uv's standalone Python (not venv) for consistent builtin modules
    UV_PYTHON=$(uv python find)
    if [ -n "$UV_PYTHON" ] && [ -x "$UV_PYTHON" ]; then
        # Write to .cargo/config.toml for persistent build-time configuration
        mkdir -p .cargo
        cat > .cargo/config.toml << EOF
# Auto-generated by setup-dev.sh - DO NOT EDIT
# This ensures PyO3 uses uv's Python for consistent builtin modules
[env]
PYO3_PYTHON = "$UV_PYTHON"
EOF
        echo -e "${GREEN}✅${NC} PYO3_PYTHON auto-configured: $UV_PYTHON"
    else
        echo -e "${YELLOW}⚠️${NC} Could not detect uv Python, using default"
    fi
else
    echo "🔗 Skipping PYO3 configuration (no pyproject.toml)"
fi

# Install pre-commit hooks
echo
echo "🔗 Installing pre-commit hooks..."
git config core.hooksPath .githooks
echo -e "${GREEN}✅${NC} Pre-commit hooks installed"

# Configure safe merge strategy (prevent accidental merge commits)
echo
echo "🛡️  Configuring safe merge strategy..."
git config pull.ff only
echo -e "${GREEN}✅${NC} pull.ff=only (safe merge) configured"

echo
echo "=========================================="
echo -e "${GREEN}✨ Setup complete! You're ready to develop.${NC}"
echo
echo "Quick commands:"
echo "  cargo build --release     # Build"
echo "  cargo test                # Rust tests"
echo "  uv run pytest             # Python tests"
echo "  cargo clippy              # Lint"
echo "=========================================="
