#!/bin/bash
# ============================================================================
# VRift QA Suite - Unified Test Runner with Report Generation
# ============================================================================
# Usage: ./scripts/qa_full_suite.sh [--quick]
#
# Runs all tests from tests/qa_v2, tests/poc, and scripts/ demos
# Generates a markdown report at /tmp/vrift_qa_report.md

set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
REPORT_FILE="/tmp/vrift_qa_report.md"
TIMEOUT_SEC=30

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# macOS compatible timeout using perl
run_with_timeout() {
    local timeout="$1"
    shift
    perl -e 'alarm shift; exec @ARGV' "$timeout" bash "$@" 2>&1
    return $?
}

# Counters
PASSED=0
FAILED=0
TIMEOUT=0
SKIPPED=0
declare -a RESULTS=()

# Run a single test
run_test() {
    local category="$1"
    local script="$2"
    local name=$(basename "$script")
    
    echo -n -e "${BLUE}[$category]${NC} $name ... "
    
    # Skip known problematic tests
    if [[ "$script" == *"test_shim_init_hang"* ]]; then
        echo -e "${YELLOW}SKIP${NC} (known hang)"
        SKIPPED=$((SKIPPED+1))
        RESULTS+=("| $category | $name | ⏭️ SKIP | Known hang issue |")
        return
    fi
    
    local output
    local start_time=$(date +%s)
    
    run_with_timeout "$TIMEOUT_SEC" "$script" > /tmp/test_output_$$.log 2>&1
    local exit_code=$?
    
    local end_time=$(date +%s)
    local duration=$((end_time - start_time))
    
    if [ $exit_code -eq 0 ]; then
        PASSED=$((PASSED+1))
        echo -e "${GREEN}PASS${NC} (${duration}s)"
        RESULTS+=("| $category | $name | ✅ PASS | ${duration}s |")
    elif [ $exit_code -eq 142 ]; then
        TIMEOUT=$((TIMEOUT+1))
        echo -e "${YELLOW}TIMEOUT${NC} (${TIMEOUT_SEC}s)"
        RESULTS+=("| $category | $name | ⏱️ TIMEOUT | >${TIMEOUT_SEC}s |")
    else
        FAILED=$((FAILED+1))
        echo -e "${RED}FAIL${NC} (exit=$exit_code)"
        # Capture last 3 lines of output for report
        local last_lines=$(tail -3 /tmp/test_output_$$.log 2>/dev/null | tr '\n' ' ' | cut -c1-60)
        RESULTS+=("| $category | $name | ❌ FAIL | $last_lines |")
    fi
    
    rm -f /tmp/test_output_$$.log
}

# Build first
echo "================================================================"
echo -e "${BLUE}VRift QA Full Suite${NC}"
echo "================================================================"
echo ""
echo "🔨 Building release binaries (including shim)..."
cd "$PROJECT_ROOT"
cargo build --release --quiet 2>/dev/null || {
    echo -e "${RED}Build failed!${NC}"
    exit 1
}
# Ensure shim cdylib is built (may not be built by --workspace alone)
cargo build --release -p vrift-shim --quiet 2>/dev/null || true
echo -e "${GREEN}✓ Build complete${NC}"
echo ""

# Run tests by category
echo "================================================================"
echo "Running tests/qa_v2 (Value Proofs)..."
echo "================================================================"
for t in "$PROJECT_ROOT"/tests/qa_v2/test_*.sh; do
    [ -f "$t" ] && run_test "qa_v2" "$t"
done

echo ""
echo "================================================================"
echo "Running scripts/ demos (E2E)..."
echo "================================================================"
for t in "$PROJECT_ROOT"/scripts/demo_*.sh; do
    [ -f "$t" ] && run_test "demo" "$t"
done

echo ""
echo "================================================================"
echo "Running tests/poc (Gap Analysis)..."
echo "================================================================"
[ -f "$PROJECT_ROOT/tests/poc/run_gap_suite.sh" ] && run_test "poc" "$PROJECT_ROOT/tests/poc/run_gap_suite.sh"

# Generate report
echo ""
echo "================================================================"
echo "Generating Report..."
echo "================================================================"

TOTAL=$((PASSED + FAILED + TIMEOUT + SKIPPED))
PASS_RATE=$(echo "scale=1; $PASSED * 100 / $TOTAL" | bc 2>/dev/null || echo "N/A")

cat > "$REPORT_FILE" << EOF
# VRift QA Report

**Generated:** $(date '+%Y-%m-%d %H:%M:%S')  
**Platform:** $(uname -s) $(uname -m)

## Summary

| Metric | Count |
|--------|-------|
| ✅ Passed | $PASSED |
| ❌ Failed | $FAILED |
| ⏱️ Timeout | $TIMEOUT |
| ⏭️ Skipped | $SKIPPED |
| **Total** | **$TOTAL** |
| **Pass Rate** | **${PASS_RATE}%** |

## Test Results

| Category | Test | Status | Notes |
|----------|------|--------|-------|
EOF

for result in "${RESULTS[@]}"; do
    echo "$result" >> "$REPORT_FILE"
done

cat >> "$REPORT_FILE" << EOF

---
*Report generated by \`scripts/qa_full_suite.sh\`*
EOF

echo ""
echo "================================================================"
echo -e "${GREEN}QA SUITE COMPLETE${NC}"
echo "================================================================"
echo ""
echo -e "  ✅ Passed:  $PASSED"
echo -e "  ❌ Failed:  $FAILED"
echo -e "  ⏱️ Timeout: $TIMEOUT"
echo -e "  ⏭️ Skipped: $SKIPPED"
echo -e "  📊 Pass Rate: ${PASS_RATE}%"
echo ""
echo -e "📄 Report saved to: ${BLUE}$REPORT_FILE${NC}"

# Exit with failure if any tests failed
[ $FAILED -eq 0 ] && [ $TIMEOUT -eq 0 ] || exit 1
